---
- name: Extract hostname of the client
  hosts: all
  gather_facts: yes
  tasks:
    - name: Display the hostname
      debug:
        msg: "The hostname of this client is {{ ansible_hostname }}"
